name: Do not manually update the binaries

on:
  pull_request:
    branches:
      - master

jobs:
  check_no_binary:
    name: Do not include release binaries in a pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - shell: bash
        id: check_binary_files_changed
        env:
          BINARY_DIRECTORY_PATH: addons/dijkstra-map/dijkstra_map_library/bin/
        run: |
          DIFF_LIST=$(git diff --name-only HEAD^ HEAD)
          if grep -q "^$BINARY_DIRECTORY_PATH" <<< "$DIFF_LIST"; then
              FILE_CHANGED=True
              exit 1
          else
              FILE_CHANGED=False
              exit 0
          fi
